// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSY7mA2SnvSI-rEKiZF8RoP_WWH1Zxcw8',
    appId: '1:836033098136:web:83e740e4b85960ee6c3bed',
    messagingSenderId: '836033098136',
    projectId: 'crested-gecko-22172',
    authDomain: 'crested-gecko-22172.firebaseapp.com',
    storageBucket: 'crested-gecko-22172.appspot.com',
    measurementId: 'G-17WBXGPY12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFhapTmR6mVEF2agsRlMSaWd0UN328l4',
    appId: '1:836033098136:android:35cb5aa2c2f499fa6c3bed',
    messagingSenderId: '836033098136',
    projectId: 'crested-gecko-22172',
    storageBucket: 'crested-gecko-22172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5tYt2IXEQZP0wk6dgFTIA-H1Cig8y3_I',
    appId: '1:836033098136:ios:3b7b7731f3ea29096c3bed',
    messagingSenderId: '836033098136',
    projectId: 'crested-gecko-22172',
    storageBucket: 'crested-gecko-22172.appspot.com',
    iosClientId: '836033098136-4d7c1uj7q4lgkk71ukm352fje6vca1ue.apps.googleusercontent.com',
    iosBundleId: 'net.crestedgecko.crestedgecko',
  );
}
